const UPDATE_CURRENT_CONDITION = 'UPDATE_CURRENT_CONDITION';
const UPDATE_TODAY_FORECAST = 'UPDATE_TODAY_FORECAST';
const UPDATE_IS_LOADING = 'UPDATE_IS_LOADING';
const SET_ERROR = 'SET_ERROR';

export { UPDATE_CURRENT_CONDITION, UPDATE_TODAY_FORECAST, UPDATE_IS_LOADING, SET_ERROR };